spring.main.banner-mode: off
spring.application.name: Validation Demo

server:
  port: 7070
  forward-headers-strategy: native
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always